### ISSUE TITLE
Namespace yaml deploy is not yet supported

### ISSUE THREAD

**Issue by khiemips** [jenkinsci/azure-acs-plugin#14]
Basicly I can use `kubectl apply -f somenamespace.yaml` to create new namespace.
https://kubernetes.io/docs/tasks/administer-cluster/namespaces/

But currently it is not supported with acs-plugin. Please help consider this feature. Thanks

**Comment by ArieShout** [comment]
At the very beginning, we consider the namespace as the top-level group for resources and it's less likely to be updated from build to build. So we excluded it from the support list as Jenkins should mainly deal with continuous deploy/integration tasks.

May I know your use case? If there's cases we didn't count in, we can add support in future versions.

Thanks,

**Comment by khiemips** [comment]
Hi,
I’m building some microservices and have a few WebAPI projects in one Git repos.

There is multiple environments to build those APIs I would like to have separated namespace for each environment.

I would like it to be dynamic based on remote branch names. For example, europe-master branch will be built to europe-master namespace…

I know it is something can be done manually on Kubernetes side, but it’s better for us to have it automated on Jenkins UI, so new users can setup new environment quickly without going to kubectl.

Thanks and best regards,
Khiem
