### ISSUE TITLE
java.lang.ClassNotFoundException: com.microsoft.jenkins.kubernetes.KubernetesClientWrapper

### ISSUE THREAD

**Issue by vmbears-marcello** [jenkinsci/azure-acs-plugin#18]
See... someone from “Kubernetes Continuous Deploy Plugin”  has changed package for KubernetesClientWrapper and now KubernetesDeploymentCommandBase can no find it anymore in the classpath and throws java.lang.ClassNotFoundException: com.microsoft.jenkins.kubernetes.KubernetesClientWrapper

Is there any fast way for releasing a new version Of  Azure-Acs-Plugin targetting this new package??

**Comment by gavinfish** [comment]
Thanks for reporting this issue. Does it mean that you just upgrade the kubernetes-cd plugin's version to 3.0.0?

**Comment by gavinfish** [comment]
Fixed in 1.0.0

**Comment by vmbears-marcello** [comment]
where is the best place to download 1.0.0 from?  
i´ve seem http://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/kubernetes-cd/1.0.0/
but looks to be built in "31-May-2019 09:28"...
Is there any good place to get the one you fixed in?
Thanks

**Comment by gavinfish** [comment]
@vmbears-marcello I have released the new version, no need to downgrade the kubernetes cd plugin. The new version should be available in the Jenkins plugin manager within several hours.

**Comment by vmbears-marcello** [comment]
Sorry for the last stupid question:
Which api deployment template are these plugin versions compatible with?
I upgrade acs for 1.0.0 and k-ci for 2.0.1 but now it seems that my templates are not good anymore...
Things like these:
"
ERROR: ERROR: Cannot create property=spec for JavaBean=class V1Deployment {
    apiVersion: apps/v1
    kind: Deployment
"

"
in 'reader', line 1, column 1:
    apiVersion: apps/v1
    ^
Cannot create property=ttlSecondsAfterFinished for JavaBean=class V1DeploymentSpec {
    minReadySeconds: null
    paused: null
    progressDeadlineSeconds: null
    replicas: null
    revisionHistoryLimit: null
    selector: null
    strategy: null
    template: null
}
 in 'reader', line 6, column 3:
      ttlSecondsAfterFinished: 2
      ^
Unable to find property 'ttlSecondsAfterFinished' on class: io.kubernetes.client.models.V1DeploymentSpec
 in 'reader', line 6, column 28:
      ttlSecondsAfterFinished: 2
                               ^

 in 'reader', line 6, column 3:
      ttlSecondsAfterFinished: 2
      ^

Cannot create property=spec for JavaBean=class V1Deployment {
    apiVersion: apps/v1
    kind: Deployment
    metadata: class V1ObjectMeta {
        annotations: null
        clusterName: null
        creationTimestamp: null
        deletionGracePeriodSeconds: null
        deletionTimestamp: null
        finalizers: null
        generateName: null
        generation: null
        initializers: null
        labels: null
        name: brmalls-ms-tools-carga-sendingtableevents-deployment
        namespace: null
        ownerReferences: null
        resourceVersion: null
        selfLink: null
        uid: null
    }
    spec: null
    status: null
}
 in 'reader', line 1, column 1:
    apiVersion: apps/v1
    ^
Cannot create property=ttlSecondsAfterFinished for JavaBean=class V1DeploymentSpec {
    minReadySeconds: null
    paused: null
    progressDeadlineSeconds: null
    replicas: null
    revisionHistoryLimit: null
    selector: null
    strategy: null
    template: null
}
 in 'reader', line 6, column 3:
      ttlSecondsAfterFinished: 2
      ^
Unable to find property 'ttlSecondsAfterFinished' on class: io.kubernetes.client.models.V1DeploymentSpec
 in 'reader', line 6, column 28:
      ttlSecondsAfterFinished: 2
                               ^

 in 'reader', line 6, column 3:
      ttlSecondsAfterFinished: 2
      ^
"
