### ISSUE TITLE
java.lang.NoSuchMethodError: com.microsoft.jenkins.kubernetes.wrapper.KubernetesClientWrapper.getClient()Lio/kubernetes/client/ApiClient;

### ISSUE THREAD

**Issue by aglees** [jenkinsci/azure-acs-plugin#24]
We've recently lost the ability to deploy via Jenkins to AKS, and are seeing the following errors. Details of the setup are:

**AKS Version:** 1.15.5
**Jenkins Version:** 2.204.1
**ACS Plugin Version:** 1.0.0
**Az-Cli:** 2.0.80
**Kubectl Client Version:** v1.17.2

Let me know if you need anything else.

`17:09:54  ERROR: ERROR: Remote call on jenkins-spot-slave5459e0 failed
17:09:54  java.io.IOException: Remote call on jenkins-spot-slave5459e0 failed
17:09:54  	at hudson.remoting.Channel.call(Channel.java:961)
17:09:54  	at hudson.FilePath.act(FilePath.java:1159)
17:09:54  	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase.doExecute(KubernetesDeploymentCommandBase.java:78)
17:09:54  	at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:32)
17:09:54  	at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:20)
17:09:54  	at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
17:09:54  	at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
17:09:54  	at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
17:09:54  	at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
17:09:54  	at com.microsoft.jenkins.acs.ACSDeploymentBuilder.perform(ACSDeploymentBuilder.java:56)
17:09:54  	at com.microsoft.jenkins.acs.ACSDeploymentContext$ExecutionImpl.run(ACSDeploymentContext.java:141)
17:09:54  	at com.microsoft.jenkins.acs.ACSDeploymentContext$ExecutionImpl.run(ACSDeploymentContext.java:125)
17:09:54  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
17:09:54  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17:09:54  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17:09:54  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
17:09:54  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
17:09:54  	at java.lang.Thread.run(Thread.java:748)
17:09:54  Caused by: java.lang.NoSuchMethodError: com.microsoft.jenkins.kubernetes.wrapper.KubernetesClientWrapper.getClient()Lio/kubernetes/client/ApiClient;
17:09:54  	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.getMasterHost(KubernetesDeploymentCommandBase.java:222)
17:09:54  	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.call(KubernetesDeploymentCommandBase.java:193)
17:09:54  	at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase$KubernetesDeployWorker.call(KubernetesDeploymentCommandBase.java:132)
17:09:54  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
17:09:54  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
17:09:54  	at hudson.remoting.Request$2.run(Request.java:369)
17:09:54  	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
17:09:54  	... 4 more
17:09:54  	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to jenkins-spot-slave5459e0
17:09:54  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
17:09:54  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
17:09:54  		at hudson.remoting.Channel.call(Channel.java:955)
17:09:54  		at hudson.FilePath.act(FilePath.java:1159)
17:09:54  		at com.microsoft.jenkins.acs.commands.KubernetesDeploymentCommandBase.doExecute(KubernetesDeploymentCommandBase.java:78)
17:09:54  		at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:32)
17:09:54  		at com.microsoft.jenkins.acs.commands.AKSDeploymentCommand.execute(AKSDeploymentCommand.java:20)
17:09:54  		at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
17:09:54  		at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
17:09:54  		at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
17:09:54  		at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
17:09:54  		at com.microsoft.jenkins.acs.ACSDeploymentBuilder.perform(ACSDeploymentBuilder.java:56)
17:09:54  		at com.microsoft.jenkins.acs.ACSDeploymentContext$ExecutionImpl.run(ACSDeploymentContext.java:141)
17:09:54  		at com.microsoft.jenkins.acs.ACSDeploymentContext$ExecutionImpl.run(ACSDeploymentContext.java:125)
17:09:54  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
17:09:54  		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17:09:54  		... 4 more
17:09:54  Delete Kubernetes management config file /home/vmadmin/jenkins/workspace/{redacted}/kubeconfig-2924573650847730029
[Pipeline] echo
17:09:54  Failed: hudson.AbortException: Azure Container Service / Kubernetes Service deployment ended with HasError`

**Comment by gavinfish** [comment]
This issue should be introduced by the upgrade of kubernetes sdk in jenkinsci/kubernetes-cd-plugin#116, and I will provide a fix here. A temporary solution should be downgrade the version of kubernetes-cd-plugin.

**Comment by gavinfish** [comment]
Fixed by 1.0.1.
